version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latestinception
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - my_network

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
        device: /Users/zelabbas/Desktop/data_base
        type: none
        o: bind

networks:
  my_network:
    driver: bridge
