version: '3'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latestinception
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_db:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - my_network

  nginx:
    build: ./requirements/nginx
    image: nginx:latestinception
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always
    ports:
      - '443:443'
    volumes:
      - wp_data:/var/www/html
    networks:
      - my_network
    
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latestinception
    depends_on:
      - mariadb
    container_name: wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wp_data:/var/www/html
    expose:
      - '9000'
    networks:
     - my_network

  static-web-site:
    build: ./requirements/bonus/static-web-site
    image: web-site:my_site
    container_name: static_site
    restart: always
    ports:
      - "80:80"
    networks:
      - my_network

  redis:
    build: ./requirements/bonus/redis-cache
    image: redis:inception
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    
  ftp:
    build: ./requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    env_file:
      - .env
    volumes:
      - wp_data:/home/zakaria/ftp
    restart: always
    ports:
      - "21:21"
      - "20:20"
      - "40011-40020:40011-40020"
    networks:
      - my_network

volumes:
  mariadb_db:
    driver: local
    driver_opts:
        device: /home/zelabbas/Desktop/data_base
        type: none
        o: bind
  wp_data:
    driver: local
    driver_opts: 
      device: /home/zelabbas/Desktop/wp_files
      type: none
      o: bind

networks:
  my_network:
    driver: bridge

# o: The o option is used to set additional options. 
# In your case, bind indicates that you're creating a bind mount, 
# which allows you to link a directory on the host filesystem directly to a container.