# Base image: Debian 12 (Bookworm)
FROM debian:bookworm

# Update packages and install necessary dependencies
RUN apt update && apt install -y curl

# Install Portainer
RUN curl -L https://github.com/portainer/portainer/releases/download/2.19.1/portainer -o /usr/local/bin/portainer && \
    chmod +x /usr/local/bin/portainer

# Expose Portainer's web interface
EXPOSE 9000

# Run Portainer
CMD ["portainer", "--no-auth", "-H", "unix:///var/run/docker.sock"]