FROM debian:bookworm

# Install curl to fetch Portainer
RUN apt update && apt install -y curl

# Download the correct Portainer binary (replace the version with the latest one if needed)
RUN curl -L https://github.com/portainer/portainer/releases/download/2.18.4/portainer-2.18.4-linux-amd64.tar.gz -o /tmp/portainer.tar.gz \
    && tar xzf /tmp/portainer.tar.gz -C /usr/local/bin/ \
    && rm /tmp/portainer.tar.gz

# Ensure the binary has the correct permissions
RUN chmod +x /usr/local/bin/portainer


# Start Portainer
CMD ["/usr/local/bin/portainer/portainer", "-H", "unix:///var/run/docker.sock"]
